import type { ProcessedRecord } from '@/hooks/useDataProcessor';

export const DEMO_DATA: ProcessedRecord[] = [
  // ETN: João Silva - 5 oportunidades
  // Empresa A tem 2 oportunidades: OPP001 (com agenda) e OPP013 (sem agenda, sequencial maior)
  {
    oppId: 'OPP001',
    conta: 'Empresa A',
    contaId: 'CONTA001',
    representante: 'Maria Santos',
    responsavel: 'Carlos',
    etn: 'João Silva',
    etapa: 'Fechada e Ganha',
    probabilidade: '100%',
    probNum: 100,
    anoPrevisao: '2026',
    mesPrevisao: 'Janeiro',
    mesPrevisaoNum: 1,
    mesFech: 'Janeiro',
    valorPrevisto: 150000,
    valorFechado: 150000,
    valorReconhecido: 200000,
    valorFechadoReconhecido: 150000,
    valorUnificado: 150000,
    percentualReconhecimento: 100,
    agenda: 5,
    tipoOportunidade: 'Venda',
    subtipoOportunidade: 'Produto',
    origemOportunidade: 'Inbound',
    motivoFechamento: 'Ganho',
    motivoPerda: '',
    concorrentes: 'Nenhum',
    cidade: 'São Paulo',
    estado: 'SP',
    cnaeSegmento: 'Tecnologia',
    categoriaCompromisso: 'Reunião',
    atividadeCompromisso: 'Apresentação',
  },
  {
    oppId: 'OPP002',
    conta: 'Empresa B',
    contaId: 'CONTA002',
    representante: 'Maria Santos',
    responsavel: 'Carlos',
    etn: 'João Silva',
    etapa: 'Negociação',
    probabilidade: '80%',
    probNum: 80,
    anoPrevisao: '2026',
    mesPrevisao: 'Fevereiro',
    mesPrevisaoNum: 2,
    mesFech: 'Fevereiro',
    valorPrevisto: 80000,
    valorFechado: 0,
    valorReconhecido: 80000,
    valorFechadoReconhecido: 0,
    valorUnificado: 0,
    percentualReconhecimento: 100,
    agenda: 3,
    tipoOportunidade: 'Novo Negócio',
    subtipoOportunidade: 'Serviço',
    origemOportunidade: 'Outbound',
    motivoFechamento: '',
    motivoPerda: '',
    concorrentes: 'Concorrente X',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    cnaeSegmento: 'Consultoria',
    categoriaCompromisso: 'Visita',
    atividadeCompromisso: 'Negociação',
  },
  {
    oppId: 'OPP003',
    conta: 'Empresa C',
    contaId: 'CONTA003',
    representante: 'Pedro Costa',
    responsavel: 'Ana',
    etn: 'João Silva',
    etapa: 'Fechada e Perdida',
    probabilidade: '0%',
    probNum: 0,
    anoPrevisao: '2026',
    mesPrevisao: 'Janeiro',
    mesPrevisaoNum: 1,
    mesFech: 'Janeiro',
    valorPrevisto: 100000,
    valorFechado: 0,
    valorReconhecido: 100000,
    valorFechadoReconhecido: 0,
    valorUnificado: 0,
    percentualReconhecimento: 100,
    agenda: 2,
    tipoOportunidade: 'Renovação',
    subtipoOportunidade: 'Produto',
    origemOportunidade: 'Inbound',
    motivoFechamento: 'Perdido',
    motivoPerda: 'Preço',
    concorrentes: 'Concorrente Y',
    cidade: 'Belo Horizonte',
    estado: 'MG',
    cnaeSegmento: 'Varejo',
    categoriaCompromisso: 'Email',
    atividadeCompromisso: 'Proposta',
  },
  {
    oppId: 'OPP004',
    conta: 'Empresa D',
    contaId: 'CONTA004',
    representante: 'Ana Silva',
    responsavel: 'Roberto',
    etn: 'João Silva',
    etapa: 'Qualificação',
    probabilidade: '50%',
    probNum: 50,
    anoPrevisao: '2026',
    mesPrevisao: 'Março',
    mesPrevisaoNum: 3,
    mesFech: 'Março',
    valorPrevisto: 75000,
    valorFechado: 0,
    valorReconhecido: 75000,
    valorFechadoReconhecido: 0,
    valorUnificado: 0,
    percentualReconhecimento: 100,
    agenda: 1,
    tipoOportunidade: 'Novo Negócio',
    subtipoOportunidade: 'Produto',
    origemOportunidade: 'Referência',
    motivoFechamento: '',
    motivoPerda: '',
    concorrentes: 'Nenhum',
    cidade: 'Brasília',
    estado: 'DF',
    cnaeSegmento: 'Governo',
    categoriaCompromisso: 'Ligação',
    atividadeCompromisso: 'Descoberta',
  },
  {
    oppId: 'OPP005',
    conta: 'Empresa E',
    contaId: 'CONTA005',
    representante: 'Lucas Oliveira',
    responsavel: 'Fernanda',
    etn: 'João Silva',
    etapa: 'Fechada e Ganha',
    probabilidade: '100%',
    probNum: 100,
    anoPrevisao: '2026',
    mesPrevisao: 'Fevereiro',
    mesPrevisaoNum: 2,
    mesFech: 'Fevereiro',
    valorPrevisto: 250000,
    valorFechado: 250000,
    valorReconhecido: 500000,
    valorFechadoReconhecido: 250000,
    valorUnificado: 250000,
    percentualReconhecimento: 100,
    agenda: 8,
    tipoOportunidade: 'Venda',
    subtipoOportunidade: 'Serviço',
    origemOportunidade: 'Inbound',
    motivoFechamento: 'Ganho',
    motivoPerda: '',
    concorrentes: 'Nenhum',
    cidade: 'Salvador',
    estado: 'BA',
    cnaeSegmento: 'Educação',
    categoriaCompromisso: 'Reunião',
    atividadeCompromisso: 'Fechamento',
  },

  // ETN: Marina Costa - 4 oportunidades
  // Empresa F tem 2 oportunidades: OPP006 (com agenda) e OPP014 (sem agenda, sequencial maior)
  {
    oppId: 'OPP006',
    conta: 'Empresa F',
    contaId: 'CONTA006',
    representante: 'Marina Costa',
    responsavel: 'Diego',
    etn: 'Marina Costa',
    etapa: 'Fechada e Ganha',
    probabilidade: '100%',
    probNum: 100,
    anoPrevisao: '2026',
    mesPrevisao: 'Janeiro',
    mesPrevisaoNum: 1,
    mesFech: 'Janeiro',
    valorPrevisto: 180000,
    valorFechado: 180000,
    valorReconhecido: 180000,
    valorFechadoReconhecido: 180000,
    valorUnificado: 180000,
    percentualReconhecimento: 100,
    agenda: 6,
    tipoOportunidade: 'Venda',
    subtipoOportunidade: 'Produto',
    origemOportunidade: 'Inbound',
    motivoFechamento: 'Ganho',
    motivoPerda: '',
    concorrentes: 'Nenhum',
    cidade: 'Curitiba',
    estado: 'PR',
    cnaeSegmento: 'Manufatura',
    categoriaCompromisso: 'Reunião',
    atividadeCompromisso: 'Apresentação',
  },
  {
    oppId: 'OPP007',
    conta: 'Empresa G',
    contaId: 'CONTA007',
    representante: 'Marina Costa',
    responsavel: 'Diego',
    etn: 'Marina Costa',
    etapa: 'Negociação',
    probabilidade: '85%',
    probNum: 85,
    anoPrevisao: '2026',
    mesPrevisao: 'Fevereiro',
    mesPrevisaoNum: 2,
    mesFech: 'Fevereiro',
    valorPrevisto: 220000,
    valorFechado: 0,
    valorReconhecido: 220000,
    valorFechadoReconhecido: 0,
    valorUnificado: 0,
    percentualReconhecimento: 100,
    agenda: 4,
    tipoOportunidade: 'Renovação',
    subtipoOportunidade: 'Serviço',
    origemOportunidade: 'Outbound',
    motivoFechamento: '',
    motivoPerda: '',
    concorrentes: 'Concorrente Z',
    cidade: 'Porto Alegre',
    estado: 'RS',
    cnaeSegmento: 'Logística',
    categoriaCompromisso: 'Visita',
    atividadeCompromisso: 'Negociação',
  },
  {
    oppId: 'OPP008',
    conta: 'Empresa H',
    contaId: 'CONTA008',
    representante: 'Marina Costa',
    responsavel: 'Diego',
    etn: 'Marina Costa',
    etapa: 'Fechada e Perdida',
    probabilidade: '0%',
    probNum: 0,
    anoPrevisao: '2026',
    mesPrevisao: 'Janeiro',
    mesPrevisaoNum: 1,
    mesFech: 'Janeiro',
    valorPrevisto: 95000,
    valorFechado: 0,
    valorReconhecido: 95000,
    valorFechadoReconhecido: 0,
    valorUnificado: 0,
    percentualReconhecimento: 100,
    agenda: 2,
    tipoOportunidade: 'Venda',
    subtipoOportunidade: 'Produto',
    origemOportunidade: 'Inbound',
    motivoFechamento: 'Perdido',
    motivoPerda: 'Falta de Budget',
    concorrentes: 'Concorrente W',
    cidade: 'Fortaleza',
    estado: 'CE',
    cnaeSegmento: 'Varejo',
    categoriaCompromisso: 'Email',
    atividadeCompromisso: 'Proposta',
  },
  {
    oppId: 'OPP009',
    conta: 'Empresa I',
    contaId: 'CONTA009',
    representante: 'Marina Costa',
    responsavel: 'Diego',
    etn: 'Marina Costa',
    etapa: 'Qualificação',
    probabilidade: '60%',
    probNum: 60,
    anoPrevisao: '2026',
    mesPrevisao: 'Março',
    mesPrevisaoNum: 3,
    mesFech: 'Março',
    valorPrevisto: 130000,
    valorFechado: 0,
    valorReconhecido: 32500,
    valorFechadoReconhecido: 0,
    valorUnificado: 0,
    percentualReconhecimento: 25,
    agenda: 1,
    tipoOportunidade: 'Renovação',
    subtipoOportunidade: 'Produto',
    origemOportunidade: 'Referência',
    motivoFechamento: '',
    motivoPerda: '',
    concorrentes: 'Nenhum',
    cidade: 'Manaus',
    estado: 'AM',
    cnaeSegmento: 'Tecnologia',
    categoriaCompromisso: 'Ligação',
    atividadeCompromisso: 'Descoberta',
  },

  // ETN: Rafael Mendes - 3 oportunidades
  // Empresa J tem 2 oportunidades: OPP010 (com agenda) e OPP015 (sem agenda, sequencial maior)
  {
    oppId: 'OPP010',
    conta: 'Empresa J',
    contaId: 'CONTA010',
    representante: 'Rafael Mendes',
    responsavel: 'Juliana',
    etn: 'Rafael Mendes',
    etapa: 'Fechada e Ganha',
    probabilidade: '100%',
    probNum: 100,
    anoPrevisao: '2026',
    mesPrevisao: 'Fevereiro',
    mesPrevisaoNum: 2,
    mesFech: 'Fevereiro',
    valorPrevisto: 320000,
    valorFechado: 320000,
    valorReconhecido: 400000,
    valorFechadoReconhecido: 320000,
    valorUnificado: 320000,
    percentualReconhecimento: 100,
    agenda: 7,
    tipoOportunidade: 'Venda',
    subtipoOportunidade: 'Serviço',
    origemOportunidade: 'Inbound',
    motivoFechamento: 'Ganho',
    motivoPerda: '',
    concorrentes: 'Nenhum',
    cidade: 'Recife',
    estado: 'PE',
    cnaeSegmento: 'Consultoria',
    categoriaCompromisso: 'Reunião',
    atividadeCompromisso: 'Apresentação',
  },
  {
    oppId: 'OPP011',
    conta: 'Empresa K',
    contaId: 'CONTA011',
    representante: 'Rafael Mendes',
    responsavel: 'Juliana',
    etn: 'Rafael Mendes',
    etapa: 'Negociação',
    probabilidade: '90%',
    probNum: 90,
    anoPrevisao: '2026',
    mesPrevisao: 'Março',
    mesPrevisaoNum: 3,
    mesFech: 'Março',
    valorPrevisto: 280000,
    valorFechado: 0,
    valorReconhecido: 280000,
    valorFechadoReconhecido: 0,
    valorUnificado: 0,
    percentualReconhecimento: 100,
    agenda: 2,
    tipoOportunidade: 'Novo Negócio',
    subtipoOportunidade: 'Consultoria',
    origemOportunidade: 'Indicação',
    motivoFechamento: '',
    motivoPerda: '',
    concorrentes: '',
    cidade: 'Brasília',
    estado: 'DF',
    cnaeSegmento: 'Governo',
    categoriaCompromisso: 'Visita',
    atividadeCompromisso: 'Negociação',
  },
  {
    oppId: 'OPP012',
    conta: 'Empresa L',
    contaId: 'CONTA012',
    representante: 'Rafael Mendes',
    responsavel: 'Juliana',
    etn: 'Rafael Mendes',
    etapa: 'Qualificação',
    probabilidade: '40%',
    probNum: 40,
    anoPrevisao: '2026',
    mesPrevisao: 'Abril',
    mesPrevisaoNum: 4,
    mesFech: 'Abril',
    valorPrevisto: 85000,
    valorFechado: 0,
    valorReconhecido: 85000,
    valorFechadoReconhecido: 0,
    valorUnificado: 0,
    percentualReconhecimento: 100,
    agenda: 2,
    tipoOportunidade: 'Venda',
    subtipoOportunidade: 'Produto',
    origemOportunidade: 'Referência',
    motivoFechamento: '',
    motivoPerda: '',
    concorrentes: 'Nenhum',
    cidade: 'Goiânia',
    estado: 'GO',
    cnaeSegmento: 'Educação',
    categoriaCompromisso: 'Reunião',
    atividadeCompromisso: 'Descoberta',
  },

  // Oportunidades SEM agenda (para cenário de agendas faltantes)
  // Empresa A - nova oportunidade após OPP001 (João Silva atuou em OPP001)
  {
    oppId: 'OPP013',
    conta: 'Empresa A',
    contaId: 'CONTA001',
    representante: 'Maria Santos',
    responsavel: 'Carlos',
    etn: 'Sem Agenda',
    etapa: 'Qualificação',
    probabilidade: '30%',
    probNum: 30,
    anoPrevisao: '2026',
    mesPrevisao: 'Março',
    mesPrevisaoNum: 3,
    mesFech: 'Março',
    valorPrevisto: 120000,
    valorFechado: 0,
    valorReconhecido: 120000,
    valorFechadoReconhecido: 0,
    valorUnificado: 0,
    percentualReconhecimento: 100,
    agenda: 0,
    tipoOportunidade: 'Venda',
    subtipoOportunidade: 'Produto',
    origemOportunidade: 'Inbound',
    motivoFechamento: '',
    motivoPerda: '',
    concorrentes: 'Nenhum',
    cidade: 'São Paulo',
    estado: 'SP',
    cnaeSegmento: 'Tecnologia',
    categoriaCompromisso: '',
    atividadeCompromisso: '',
  },
  // Empresa F - nova oportunidade após OPP006 (Marina Costa atuou em OPP006)
  {
    oppId: 'OPP014',
    conta: 'Empresa F',
    contaId: 'CONTA006',
    representante: 'Marina Costa',
    responsavel: 'Diego',
    etn: 'Sem Agenda',
    etapa: 'Negociação',
    probabilidade: '70%',
    probNum: 70,
    anoPrevisao: '2026',
    mesPrevisao: 'Março',
    mesPrevisaoNum: 3,
    mesFech: 'Março',
    valorPrevisto: 160000,
    valorFechado: 0,
    valorReconhecido: 160000,
    valorFechadoReconhecido: 0,
    valorUnificado: 0,
    percentualReconhecimento: 100,
    agenda: 0,
    tipoOportunidade: 'Venda',
    subtipoOportunidade: 'Serviço',
    origemOportunidade: 'Inbound',
    motivoFechamento: '',
    motivoPerda: '',
    concorrentes: 'Nenhum',
    cidade: 'Curitiba',
    estado: 'PR',
    cnaeSegmento: 'Manufatura',
    categoriaCompromisso: '',
    atividadeCompromisso: '',
  },
  // Empresa J - nova oportunidade após OPP010 (Rafael Mendes atuou em OPP010)
  {
    oppId: 'OPP015',
    conta: 'Empresa J',
    contaId: 'CONTA010',
    representante: 'Rafael Mendes',
    responsavel: 'Juliana',
    etn: 'Sem Agenda',
    etapa: 'Prospecção',
    probabilidade: '20%',
    probNum: 20,
    anoPrevisao: '2026',
    mesPrevisao: 'Abril',
    mesPrevisaoNum: 4,
    mesFech: 'Abril',
    valorPrevisto: 90000,
    valorFechado: 0,
    valorReconhecido: 90000,
    valorFechadoReconhecido: 0,
    valorUnificado: 0,
    percentualReconhecimento: 100,
    agenda: 0,
    tipoOportunidade: 'Novo Negócio',
    subtipoOportunidade: 'Produto',
    origemOportunidade: 'Outbound',
    motivoFechamento: '',
    motivoPerda: '',
    concorrentes: 'Nenhum',
    cidade: 'Recife',
    estado: 'PE',
    cnaeSegmento: 'Consultoria',
    categoriaCompromisso: '',
    atividadeCompromisso: '',
  },
  // Adicionar registros com Demonstração Presencial/Remota para Taxa de Conversão
  {
    oppId: 'OPP016',
    conta: 'Empresa E',
    contaId: 'CONTA005',
    representante: 'João Costa',
    responsavel: 'Ana',
    etn: 'Eduardo Basso',
    etapa: 'Fechada e Ganha',
    probabilidade: '100%',
    probNum: 100,
    anoPrevisao: '2026',
    mesPrevisao: 'Março',
    mesPrevisaoNum: 3,
    mesFech: 'Março',
    valorPrevisto: 300000,
    valorFechado: 300000,
    valorReconhecido: 300000,
    valorFechadoReconhecido: 300000,
    valorUnificado: 300000,
    percentualReconhecimento: 100,
    agenda: 3,
    tipoOportunidade: 'Venda',
    subtipoOportunidade: 'Serviço',
    origemOportunidade: 'Inbound',
    motivoFechamento: 'Ganho',
    motivoPerda: '',
    concorrentes: 'Concorrente A',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    cnaeSegmento: 'Tecnologia',
    categoriaCompromisso: 'Demonstração Presencial',
    atividadeCompromisso: 'Apresentação',
  },
  {
    oppId: 'OPP017',
    conta: 'Empresa F',
    contaId: 'CONTA006',
    representante: 'Maria Santos',
    responsavel: 'Carlos',
    etn: 'Nádia Ramos',
    etapa: 'Fechada e Perdida',
    probabilidade: '75%',
    probNum: 75,
    anoPrevisao: '2026',
    mesPrevisao: 'Abril',
    mesPrevisaoNum: 4,
    mesFech: 'Abril',
    valorPrevisto: 250000,
    valorFechado: 0,
    valorReconhecido: 250000,
    valorFechadoReconhecido: 0,
    valorUnificado: 0,
    percentualReconhecimento: 100,
    agenda: 2,
    tipoOportunidade: 'Renovação',
    subtipoOportunidade: 'Serviço',
    origemOportunidade: 'Inbound',
    motivoFechamento: 'Perdido',
    motivoPerda: 'Preço',
    concorrentes: 'Concorrente B',
    cidade: 'Brasília',
    estado: 'DF',
    cnaeSegmento: 'Consultoria',
    categoriaCompromisso: 'Demonstração Remota',
    atividadeCompromisso: 'Webinar',
  },
  {
    oppId: 'OPP018',
    conta: 'Empresa G',
    contaId: 'CONTA007',
    representante: 'Pedro Silva',
    responsavel: 'Beatriz',
    etn: 'Andrea Aparecida',
    etapa: 'Fechada e Ganha',
    probabilidade: '100%',
    probNum: 100,
    anoPrevisao: '2026',
    mesPrevisao: 'Maio',
    mesPrevisaoNum: 5,
    mesFech: 'Maio',
    valorPrevisto: 180000,
    valorFechado: 180000,
    valorReconhecido: 180000,
    valorFechadoReconhecido: 180000,
    valorUnificado: 180000,
    percentualReconhecimento: 100,
    agenda: 4,
    tipoOportunidade: 'Venda',
    subtipoOportunidade: 'Produto',
    origemOportunidade: 'Outbound',
    motivoFechamento: 'Ganho',
    motivoPerda: '',
    concorrentes: 'Nenhum',
    cidade: 'Curitiba',
    estado: 'PR',
    cnaeSegmento: 'Tecnologia',
    categoriaCompromisso: 'Demonstração Presencial',
    atividadeCompromisso: 'Apresentação',
  },
];
